AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  StoreAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionUri: store-swagger.json
    
Outputs:

    StoreAPI:
      Description: "Root API endpoint URL for Prod stage"
      Value: !Sub "https://${StoreAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"
      Export:
        Name: StoreAPIRoot