version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file api/store-api.yml
                                   --s3-bucket demo-store-api
                                   --s3-prefix api-code
                                   --output-template-file api/store-api-output.yml
artifacts:
  type: zip
  files:
    - api/store-api-output.yml